//import './globals.css';
export const metadata = {
    title: 'Polar Lab Docs',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className='body' id='body'>{children}</body>
        </html>
    );
}
